---
title: "sICA_analysis_report_AK"
author: "Ahmed Khalil"
date: "29 Mai 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load necessary packages
library(fmsb)
library(glmnet)
library(irr) # needed to calculate Cohen's kappa
library(pROC)
library(kableExtra)
library(oro.nifti)
library(colorspace)

# raincloud plots
library(vioplot)
library(readr)
library(tidyr)
library(ggplot2)
library(Hmisc)
library(plyr)
library(RColorBrewer)
library(reshape2)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")

```


```{r, echo= FALSE, fig.width=6, fig.height=6, fig.align='center',dpi=300, warning=F,}
# load feature values
HFE_feats <- read.csv2("HFE_feats.csv", sep = ",", header = F)
# remove column representing HIC (made redundant by next steps)
HFE_feats <- HFE_feats[,-15]

# load class labels (i.e. which subject, IC #, and which IC is a HIC)
HFE_classlabels <- read.csv2("HFE_classLabels.csv", sep = ",", header =F)

# merge values and labels
HFE_full <- cbind(HFE_classlabels, HFE_feats)

# add column names to full feature matrix
colnames(HFE_full) <- c("subject", "IC_number", "HIC", "delay_WB", "xcovariance_WB", "delay_SSS", "xcovariance_SSS", "delay_SSSIC", "xcovariance_SSSIC", "power_0_001", "power_001_0025", "power_0025_005", "power_005_01", "power_01_015", "power_015_02", "occupancy_VT", "Tmax_delay")

# make sure columns have correct data type
HFE_full$subject <- as.factor(HFE_full$subject)
HFE_full$IC_number <- as.factor(HFE_full$IC_number)
HFE_full$HIC <- as.factor(HFE_full$HIC)
for (i in c(4:17)){
  HFE_full[,i] <- as.numeric(as.character(HFE_full[,i]))
  }

# divide Tmax delay by ten
HFE_full$Tmax_delay <- HFE_full$Tmax_delay/10

# remove variables not used in further analysis
HFE_full <- HFE_full[,-c(5,7,8,9)]

```


# Features - radar plots
```{r, echo= FALSE, fig.width=8, fig.height=8, fig.align='center',dpi=300, warning=F,}
# normalize all data (each feature from 0 to 1) according to this source: http://bit.ly/2lRfxS4 
# create normalize function
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))}

# create empty dataframe for normalized data
HFE_full_norm <- data.frame()

# loop through each patient
for (s in unique(HFE_full$subject)) {
  
# normalize features
HFE_full_norm_sub <- as.data.frame(lapply(HFE_full[HFE_full$subject==(s),4:13], normalize))
HFE_full_norm_sub <- cbind(HFE_full[HFE_full$subject==(s),1:3], HFE_full_norm_sub)
HFE_full_norm <- rbind.data.frame(HFE_full_norm, HFE_full_norm_sub)

}

# get normalized data frame of features of HICs & non-HICs
HFE_full_norm_HIC <- HFE_full_norm[HFE_full_norm$HIC==1,]
HFE_full_norm_nonHIC <- HFE_full_norm[HFE_full_norm$HIC==0,]

# take mean of each column (feature)
HFE_full_norm_HIC_mean <- colMeans(HFE_full_norm_HIC[,4:13], na.rm = T)
HFE_full_norm_nonHIC_mean <- colMeans(HFE_full_norm_nonHIC[,4:13], na.rm = T)

# take SEM of each column (feature) based on http://stackoverflow.com/questions/2676554/in-r-how-to-find-the-standard-error-of-the-mean
HFE_full_norm_HIC_sem <- sapply(HFE_full_norm_HIC[,4:13],function(x)sqrt(var(x, na.rm = T)/length(na.omit(x))))
HFE_full_norm_nonHIC_sem <- sapply(HFE_full_norm_nonHIC[,4:13],function(x)sqrt(var(x, na.rm = T)/length(na.omit(x))))
# take SD of each column (feature)
HFE_full_norm_HIC_sd <- apply(HFE_full_norm_HIC[,4:13],2,sd, na.rm = T)
HFE_full_norm_nonHIC_sd <- apply(HFE_full_norm_nonHIC[,4:13],2,sd, na.rm = T)

# get mean +/- 95% CI of each feature
HFE_full_norm_HIC_meanplus <- HFE_full_norm_HIC_mean+(1.96*HFE_full_norm_HIC_sem)
HFE_full_norm_HIC_meanminus <- HFE_full_norm_HIC_mean-(1.96*HFE_full_norm_HIC_sem)
features_HIC <- rbind(HFE_full_norm_HIC_meanplus, HFE_full_norm_HIC_mean, HFE_full_norm_HIC_meanminus)

HFE_full_norm_nonHIC_meanplus <- HFE_full_norm_nonHIC_mean+(1.96*HFE_full_norm_nonHIC_sem)
HFE_full_norm_nonHIC_meanminus <- HFE_full_norm_nonHIC_mean-(1.96*HFE_full_norm_nonHIC_sem)
features_nonHIC <- rbind(HFE_full_norm_nonHIC_meanplus, HFE_full_norm_nonHIC_mean, HFE_full_norm_nonHIC_meanminus)

# add minimum (0) and maximum (1) rows to all features
features_HIC <- as.data.frame(rbind(rep(1,10) , rep(0,10) , features_HIC))

# plot both HIC and non-HIC together
radar_title = c("Mean +/- 95% CI of normalized feature values")
radarchart(rbind(features_HIC, features_nonHIC), pcol = c("red", "red", "red", "blue", "blue", "blue"), plty = c(2, 1, 2, 2, 1, 2), pty = c(32, 16, 32, 32, 16, 32),  title = radar_title, plwd = c(2, 3, 2, 2, 3, 2), vlcex = 1, vlabels = c("Delay to whole-brain", "Delay to sinus", "Power 0 - 0.01 Hz", "Power 0.01 - 0.025 Hz", "Power 0.025 - 0.05 Hz", "Power 0.05 - 0.1 Hz", "Power 0.1 - 0.15 Hz", "Power 0.15 - 0.2 Hz", "VT occupancy", "Tmax delay"))


# individual radar plots
for (s in unique(HFE_full$subject)) {
  
HFE_full_norm_HIC_sub <- HFE_full_norm_HIC[HFE_full_norm_HIC$subject==s,c(-1,-2,-3)]
HFE_full_norm_nonHIC_sub <- HFE_full_norm_nonHIC[HFE_full_norm_nonHIC$subject==s,c(-1,-2,-3)]

# add minimum (0) and maximum (1) rows to all features
features_HIC_sub <- as.data.frame(rbind(rep(1,10) , rep(0,10) , HFE_full_norm_HIC_sub))
# for the cases with no HICs
if (nrow(HFE_full_norm_HIC_sub) == 0) {
  features_all_sub <- as.data.frame(rbind(rep(1,10) , rep(0,10) , HFE_full_norm_nonHIC_sub))
} else {
features_all_sub <- rbind(features_HIC_sub, HFE_full_norm_nonHIC_sub)}

# plot both HIC and non-HIC together
png(filename = paste("radar_plot_", s, ".png", sep = ""), width = 900, height = 900)
radar_title = paste("Normalized feature values for subject", s)
radarchart(features_all_sub, pcol = c(rep("red", nrow(features_HIC_sub)-2), rep("blue", nrow(HFE_full_norm_nonHIC_sub))), plwd = 2, plty = 1,  title = radar_title, vlcex = 1.5, vlabels = c("Delay to whole-brain", "Delay to sinus", "0 - 0.01 Hz", "0.01 - 0.025 Hz", "0.025 - 0.05 Hz", "0.05 - 0.1 Hz", "0.1 - 0.15 Hz", "0.15 - 0.2 Hz", "VT occupancy", "Tmax delay"))
dev.off()
}
```

# Features - within-subject comparisons
```{r, echo= FALSE, fig.width=6, fig.height=6, fig.align='center',dpi=300, warning=F}

```

# Predicting HICs
```{r, echo= FALSE, fig.width=6, fig.height=6, fig.align='center',dpi=300, warning=F, results="asis"}

# define vectors to save each (across iterations) result - NB "all" refers to all iterations of the testing phase unless otherwise specified
lambdas_all <- c() # all lambdas
coef_all <- c() # all coefficients
auc_all <- c() # all AUCs
acc_all <- c() # all accuracy values
roc_sens_all <- c() # all ROC sensitivities (all thresholds)
roc_spec_all <- c() # all ROC specificities (all thresholds)
opt_t_all <- c() # all optimal thresholds from ROC analysis (maximizes sens + spec)
opt_sens_all <- c() # all optimal sensitivities
opt_spec_all <- c() # all optimal specificities
kappa_all <- c() # all Cohen's kappas
mse_all <- c() # all MSEs

# CREATE BALANCED DATASET + TRAIN MODEL ON IT
# select the features of rows corresponding to HICs
HFE_full_HIC <- HFE_full[HFE_full$HIC==1,]
# select the features of rows corresponding to non-HICs
HFE_full_nonHIC <- HFE_full[HFE_full$HIC==0,]
# select a sample of non-HICs equal to n of HICs (indices, then features)
HFE_full_nonHIC_subsamp_index <- sample(x = nrow(HFE_full_nonHIC), size = nrow(HFE_full_HIC), replace = FALSE)
HFE_full_nonHIC_subsamp <- HFE_full_nonHIC[HFE_full_nonHIC_subsamp_index,]
# combine the HICs + nonHICs features
HFE_full_balanced_subsamp <- rbind(HFE_full_HIC, HFE_full_nonHIC_subsamp)
# split model data into training and test
# select 80% of data as sample size for training
HFE_balanced_subsamp_training_n <- floor(0.8*nrow(HFE_full_balanced_subsamp))
# find training data indices
HFE_balanced_subsamp_training_i <-sample(seq_len(nrow(HFE_full_balanced_subsamp)),size=HFE_balanced_subsamp_training_n) 
# select training data
HFE_balanced_subsamp_training <- HFE_full_balanced_subsamp[HFE_balanced_subsamp_training_i,]
# select test data
HFE_balanced_subsamp_test <- HFE_full_balanced_subsamp[-HFE_balanced_subsamp_training_i,]

# train ELASTIC NET GLM on BALANCED data
excl_var <-  c(1,2,3, 13) # variables to EXCLUDE from model

# fit model
# get lambda WARNING: IS "MSE" THE CORRECT LOSS FUNC TO USE HERE??? + THIS IS LOO CV
lasso_HFE_crossval <- cv.glmnet(x = as.matrix(HFE_balanced_subsamp_training[,-excl_var]), nfolds = nrow(HFE_balanced_subsamp_training), y = as.matrix(HFE_balanced_subsamp_training[,3]), family = "binomial", alpha = 0.5, type.measure = "mse", grouped = FALSE) 
# get the MSE corresponding to the minimum lambda according to http://bit.ly/2kW0aII
mse.min <- lasso_HFE_crossval$cvm[lasso_HFE_crossval$lambda == lasso_HFE_crossval$lambda.min]
# get coefficients
lasso_HFE_coef <- coef.glmnet(object = lasso_HFE_crossval, s = lasso_HFE_crossval$lambda.min)
# put coefficients into a proper vector
lasso_HFE_coef <- unname(lasso_HFE_coef, force = FALSE) # unname matrix
lasso_HFE_coef <- as.vector(lasso_HFE_coef) # turn matrix into a vector

for (i in 1:50) {
  # CREATE UNBALANCED (REALISTIC) TEST DATASET + VALIDATE MODEL ON IT
    # select a sample of HICs (indices) that were NOT included in the training dataset (n=5 out of possible 15)
      # get all HICS in test data
      HFE_feats_unbalanced_test_HIC <- HFE_balanced_subsamp_test[HFE_balanced_subsamp_test$HIC==1,]
      # get sample of all HICS in test data (5 out of possible 15)
      HFE_feats_unbalanced_test_HICsample <- sample(x = nrow(HFE_feats_unbalanced_test_HIC), size = 5, replace = FALSE)
      HFE_feats_unbalanced_test_HICsample_data <- HFE_feats_unbalanced_test_HIC[HFE_feats_unbalanced_test_HICsample,]
    # select a sample of non-HICs equal to 10*n of HICs (indices, then features) that were NOT included in training
      HFE_feats_unbalanced_test_nonHICsample_notrain <- HFE_full_nonHIC[-HFE_full_nonHIC_subsamp_index,] # exclude data used during training
      nonhic_feats_sampleindices_test <- sample(x = nrow(HFE_feats_unbalanced_test_nonHICsample_notrain), size = 10*length(HFE_feats_unbalanced_test_HICsample), replace = FALSE)
      nonhic_feats_sample_test <- HFE_feats_unbalanced_test_nonHICsample_notrain[nonhic_feats_sampleindices_test,]
    # combine the HICs + nonHICs features
    real_data_feats <- rbind(HFE_feats_unbalanced_test_HICsample_data, nonhic_feats_sample_test)
    
  # make predictions on REALISTIC TEST data
  real_test_predict <- predict(object = lasso_HFE_crossval, newx = as.matrix(real_data_feats[,-excl_var]), s = lasso_HFE_crossval$lambda.min, type = "response")
  real_test_predict <- as.vector(real_test_predict) # if I don't do this, "roc" gives weird warning to pass a vector instead of matrix (still runs tho)
  # assess the performance of the model on the REALISTIC TEST data
  test.class<-as.numeric(as.character(real_data_feats[,3])) # The true class, i.e. outcome
  # Assess performance in terms of AUC for training set:
  test.rocurve<-roc(response=test.class, predictor=real_test_predict) # calculate a ROC curve
  test.AUC<-test.rocurve$auc #+auc(roc=rocurve)
  # Find threshold (t) that minimizes error according to http://bit.ly/2k6UgCG 
  e <- cbind(test.rocurve$thresholds,test.rocurve$sensitivities+test.rocurve$specificities)
  opt_t <- subset(e,e[,2]==max(e[,2]))[,1]
  # find sensitivity + specificity at t
  # find row of t
  row_t <- which(x = e[,1]==opt_t)
  # match to row in sens/spec vector
  opt_sens <- test.rocurve$sensitivities[row_t]
  opt_spec <- test.rocurve$specificities[row_t]
  # define predicted classes based on threshold (t)
  test.prediction.class = real_test_predict>opt_t
  # Assess performance in terms of accuracy (%) for training set:
  test.accuracy <- 1-sum(xor(test.prediction.class, test.class))/nrow(real_data_feats)
  cmat = table(test.class, test.prediction.class) # confusion matrix (contingency table)
  # Assess performance in terms of Cohen's kappa for test set: Why? because it's insensitive to class imbalance
  test_kappa <- kappa2(cbind(test.class, test.prediction.class))$value
  # save all results (across iterations)
  auc_all <- append(auc_all, test.AUC)
  lambdas_all <- append(lambdas_all, lasso_HFE_crossval$lambda.min)
  coef_all <- cbind(coef_all, lasso_HFE_coef) 
  rownames(coef_all) <- c("intercept", colnames(real_data_feats[,-excl_var])) # put the variable names back
  OR_all <- exp(coef_all) # convert coefficients to odds ratios
  acc_all <- append(acc_all, test.accuracy)
  roc_sens_all <- cbind(roc_sens_all, test.rocurve$sensitivities)
  roc_spec_all <- cbind (roc_spec_all, test.rocurve$specificities)
  opt_t_all <- append(opt_t_all, opt_t)
  opt_sens_all <- append(opt_sens_all, opt_sens)
  opt_spec_all <- append(opt_spec_all, opt_spec)
  kappa_all <- append(kappa_all, test_kappa)
  mse_all <- append(mse_all, mse.min)}
# plot all ROC curves, one on top of the other
#matplot(1-roc_spec_all, roc_sens_all, type = "l", lwd = "2", lty = 1)
#abline(a = 0, b = 1)
 matplot(1-roc_spec_all, roc_sens_all, type = "l", lwd = "2", lty = 1, col=rgb(0,0,1, alpha=0.1))
 abline(a = 0, b = 1)
 matplot(1-rowMeans(roc_spec_all), rowMeans(roc_sens_all), type = "l", lwd = "2", lty = 2, add=TRUE)
# report main results
cat("Median performance on real test set: AUC=",median(auc_all),"\n")
cat("Median accuracy on real test set: ",median(acc_all),"\n")
cat("Median optimal sensitivity on real test set: ", median(opt_sens_all), "\n")
cat("Median optimal specificity on real test set: ", median(opt_spec_all), "\n")
cat("Median Cohen's kappa on real test set: ", median(kappa_all), "\n")

# plot model performance
# define a theme to make raincloud plots
raincloud_theme = theme(
  text = element_text(size = 20),
  axis.title.x = element_text(size = 20),
  axis.title.y = element_text(size = 20),
  axis.text = element_text(size = 14),
  legend.title=element_text(size=16),
  legend.text=element_text(size=16),
  legend.position = "right",
  plot.title = element_text(lineheight=.8, face="bold", size = 16),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
  axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'))

# prepare data for raincloud plots

par(mfrow=c(3,2))
all_stats <- cbind(auc_all,acc_all,opt_sens_all,opt_spec_all,kappa_all)
colnames(all_stats) <- c("AUC", "Accuracy", "Sensitivity", "Specificity", "Kappa")
all_stats_long <- melt(all_stats)

# plot raincloud plot
ggplot(data = all_stats_long, aes(y = value, x = Var2, fill = Var2)) +
geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .8) +
geom_point(aes(y = value, color = Var2), position = position_jitter(width = .15), size = .5, alpha = 0.8) +
geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
expand_limits(x = 5.25) +
guides(fill = FALSE) +
guides(color = FALSE) +
scale_color_brewer(palette = "Set2") +
scale_fill_brewer(palette = "Set2") +
theme_bw() +
raincloud_theme

kable(rowMeans(OR_all))
```

# Figure 2
```{r, echo= FALSE, fig.width=6, fig.height=6, fig.align='center',dpi=300, warning=F, results="asis", eval = FALSE}
epi_temp <- readNIfTI("../figures/figure2/AK_103_EPI_template_brain.nii.gz")
dwi_bl <- readNIfTI("../figures/figure2/147/dwi2epiWarped.nii.gz")
dwi_fu <- readNIfTI("../figures/figure2/148/dwi2epiWarped.nii.gz")
tmax_bl <- readNIfTI("../figures/figure2/147/Tmax_sSVD_norm.nii.gz")
tmax_fu <- readNIfTI("../figures/figure2/148/Tmax_norm.nii.gz")
IC_bl <- intersect(list.files("../figures/figure2/147/", pattern = "thresh_"), list.files("../figures/figure2/147/", pattern = ".nii.gz$"))
IC_fu <- intersect(list.files("../figures/figure2/148/", pattern = "thresh_"), list.files("../figures/figure2/148/", pattern = ".nii.gz$"))

# define jet colormap
jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))


for (f in c("epi_temp", "dwi_bl", "dwi_fu", "tmax_bl", "tmax_fu")){
  # plot single slices
  png(paste("../figures/figure2/",f,".png",sep=""))
  if (f == "tmax_bl" | f == "tmax_fu"){
  image(get(f),  z = 40, plot.type = "single", zlim=c(1,130),col=jet.colors(7))} 
  else {
  image(get(f),  z = 40, plot.type = "single")}
  dev.off()
  # plot mosaics
  png(paste("../figures/figure2/",f,"_mosaic.png",sep=""))
  if (f == "tmax_bl" | f == "tmax_fu"){
  image(get(f), zlim=c(1,130),col=jet.colors(7))} 
  else {
  image(get(f))}
  dev.off()
}

for (g in c(IC_bl)){
  # load in IC NIFTI
  ic <- readNIfTI(paste("../figures/figure2/147/",g,sep=""))
  # plot single slice
  png(paste("../figures/figure2/147/",g,".png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA), z = 40, plot.type = "single")
  dev.off()
  # plot mosaic
  png(paste("../figures/figure2/147/",g,"_mosaic.png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA))
  dev.off()
}

for (h in c(IC_fu)){
  # load in IC NIFTI
  ic <- readNIfTI(paste("../figures/figure2/148/",h,sep=""))
  # plot single slice
  png(paste("../figures/figure2/148/",h,".png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA), z = 40, plot.type = "single")
  dev.off()
  # plot mosaic
  png(paste("../figures/figure2/148/",h,"_mosaic.png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA))
  dev.off()
}

```

# Supp Figure 1
```{r, echo= FALSE, fig.width=6, fig.height=6, fig.align='center',dpi=300, warning=F, results="asis", eval = FALSE}
epi_temp <- readNIfTI("../figures/figure2/AK_103_EPI_template_brain.nii.gz")
dwi_bl <- readNIfTI("../figures/supp_fig1/28/dwi2epiWarped.nii.gz")
dwi_fu <- readNIfTI("../figures/supp_fig1/29/dwi2epiWarped.nii.gz")
tmax_bl <- readNIfTI("../figures/supp_fig1/28/Tmax_norm.nii.gz")
tmax_fu <- readNIfTI("../figures/supp_fig1/29/Tmax_norm.nii.gz")
IC_bl <- intersect(list.files("../figures/supp_fig1/28/", pattern = "thresh_"), list.files("../figures/supp_fig1/28/", pattern = ".nii.gz$"))
IC_fu <- intersect(list.files("../figures/supp_fig1/29/", pattern = "thresh_"), list.files("../figures/supp_fig1/29/", pattern = ".nii.gz$"))


for (f in c("epi_temp", "dwi_bl", "dwi_fu", "tmax_bl", "tmax_fu")){
  # plot single slices
  png(paste("../figures/supp_fig1/",f,".png",sep=""))
  if (f == "tmax_bl" | f == "tmax_fu"){
  image(get(f),  z = 44, plot.type = "single", zlim=c(1,130),col=jet.colors(7))} 
  else {
  image(get(f),  z = 44, plot.type = "single")}
  dev.off()
  # plot mosaics
  png(paste("../figures/supp_fig1/",f,"_mosaic.png",sep=""))
  if (f == "tmax_bl" | f == "tmax_fu"){
  image(get(f), zlim=c(1,130),col=jet.colors(7))} 
  else {
  image(get(f))}
  dev.off()
}

for (g in c(IC_bl)){
  # load in IC NIFTI
  ic <- readNIfTI(paste("../figures/supp_fig1/28/",g,sep=""))
  # plot single slice
  png(paste("../figures/supp_fig1/28/",g,".png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA), z = 44, plot.type = "single")
  dev.off()
  # plot mosaic
  png(paste("../figures/supp_fig1/28/",g,"_mosaic.png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA))
  dev.off()
}

for (h in c(IC_fu)){
  # load in IC NIFTI
  ic <- readNIfTI(paste("../figures/supp_fig1/29/",h,sep=""))
  # plot single slice
  png(paste("../figures/supp_fig1/29/",h,".png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA), z = 44, plot.type = "single")
  dev.off()
  # plot mosaic
  png(paste("../figures/supp_fig1/29/",h,"_mosaic.png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA))
  dev.off()
}

```

# Supp Figure 2
```{r, echo= FALSE, fig.width=6, fig.height=6, fig.align='center',dpi=300, warning=F, results="asis", eval = FALSE}
epi_temp <- readNIfTI("../figures/figure2/AK_103_EPI_template_brain.nii.gz")
dwi_bl <- readNIfTI("../figures/supp_fig2/186/dwi2epiWarped.nii.gz")
tmax_bl <- readNIfTI("../figures/supp_fig2/186/Tmax_norm.nii.gz")
IC_bl <- intersect(list.files("../figures/supp_fig2/186/", pattern = "thresh_"), list.files("../figures/supp_fig2/186/", pattern = ".nii.gz$"))


for (f in c("epi_temp", "dwi_bl", "tmax_bl")){
  # plot single slices
  png(paste("../figures/supp_fig2/",f,".png",sep=""))
  if (f == "tmax_bl"){
  image(get(f),  z = 63, plot.type = "single", zlim=c(1,130),col=jet.colors(7))} 
  else {
  image(get(f),  z = 63, plot.type = "single")}
  dev.off()
  # plot mosaics
  png(paste("../figures/supp_fig2/",f,"_mosaic.png",sep=""))
  if (f == "tmax_bl"){
  image(get(f), zlim=c(1,130),col=jet.colors(7))} 
  else {
  image(get(f))}
  dev.off()
}

for (g in c(IC_bl)){
  # load in IC NIFTI
  ic <- readNIfTI(paste("../figures/supp_fig2/186/",g,sep=""))
  # plot single slice
  png(paste("../figures/supp_fig2/186/",g,".png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA), z = 63, plot.type = "single")
  dev.off()
  # plot mosaic
  png(paste("../figures/supp_fig2/186/",g,"_mosaic.png",sep=""))
  overlay(epi_temp, ifelse(ic > 0, ic, NA))
  dev.off()
}

```